add_newline = false

# A minimal left prompt
format = """$os$directory$fill$cmd_duration$status$nodejs$git_branch
$character"""

[nodejs]
format = "[$symbol($version )](bold green)"
# Only show in node projects
detect_extensions = []
detect_files = ['package.json', '.node-version', '.nvmrc']

# [os]
# format = '[$symbol](bold #a9b1d6) '   
# disabled = false
#
# [os.symbols]
# Windows = ' '
# Arch = '󰣇'
# Ubuntu = ''
# Pop = ''
# Macos = '󰀵'
# Unknown = '󰠥'

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold #9ece6a)"  # Use the desired color here
error_symbol = "[❯](bold #db4b4b)"   # Use the desired color here
vimcmd_symbol = "[❮](bold #9ece6a)"  # Replace with your desired color

[git_branch]
format = '[$branch]($style) '
style = 'bold #9ece6a'

[directory]
style = "#7aa2f7"
truncation_symbol = ""

[cmd_duration]
min_time = 5_000
style = "#ff9e64"
format = '[$duration]($style) '

[line_break]
disabled = false

[status]
disabled = false
symbol = '✘ '
